const initialState = {
  movies: [],
  setMovies: () => {},
  getMovies: () => {},
  loading: true,
  setLoading: () => {},
  tvPopular: [],
  setTVPopular: () => {},
  getTV: () => {},
  trending: [],
  setTrending: () => {},
  getTrending: () => {},
  alignment: 'day',
  setAlignment: () => {},
  hideSearchBar: true,
  setHideSearchBar: () => {},
  searchMulti: () => {},
  searchResults: [],
  setSearchResults: () => {},
  searchMovies: () => {},
  searchTvShows: () => {},
  searchPeople: () => {},
  movieSearchResults: [],
  tvSearchResults: [],
  peopleSearchResults: [],
  details: [],
  setDetails: () => {},
  credits: [],
  setCredits: () => {},
  externalId: [],
  setExternalId: () => {},
  keywords: [],
  setKeywords: () => {},
  recommend: [],
  setRecommend: () => {},
  person: [],
  setPerson: () => {},
  personTvCre: [],
  setPersonTvCre: () => {},
  personMovieCre: [],
  setPersonMovieCre: () => {},
  personExId: [],
  setPersonExId: () => {},
};

export default initialState;
